### ISSUE TITLE
Implement deletion for policy packs

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#57] opened 2019-08-09 17:35 UTC
If you publish something like a secret, it would be nice to be able to delete a policy pack forever. Likewise for unused policy packs.

**Comment by lukehoban** [comment] 2019-12-02 14:56
Closing as a dupe of (part of) https://github.com/pulumi/pulumi/issues/3589.

**Closed by lukehoban** 2019-12-02 14:56 UTC
Labels: pac
