### ISSUE TITLE
Policy rule types should be derived from input shapes

### ISSUE THREAD

**Issue by hausdorff** [pulumi/pulumi-policy#96] opened 2019-08-29 06:30 UTC
The current regiment for creating types for policy rules (the `Resolved` family) has several drawbacks which we need to rectify. Quoting from here: https://github.com/pulumi/pulumi-policy/issues/92#issuecomment-526043628

> We actually need to transition away from `Resolved` and towards something that unwraps the `Input` shapes—`Resolved` on the `CustomResource` types (among other things) does not fully capture nullable fields, and includes output-only fields that will never be populated in an update. We meant to do this but haven't gotten to it yet because (1) the unknowns issue was much more urgent, and (2) we had to switch focus to v1 work. But, this is certainly on the list.
>
> I thought we had an issue for this, but—somehow there isn't? I'll file one.

**Comment by justinvp** [comment] 2019-11-05 21:27
Closing as a dupe of #116

**Closed by justinvp** 2019-11-05 21:27 UTC
Labels: pac, pac/ga
