### ISSUE TITLE
Strange that PolicyPack projects are real Pulumi projects

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-policy#88] opened 2019-08-28 22:41 UTC
Because we use the `Pulumi.yaml` file, the CLI thinks that PolicyPack definitions are real Pulumi programs. That leads to odd behavior, like the ability to create stacks for those projects, run CLI commands inside of them, and even letting you run `pulumi up`, which actually tries to proceed, seems to print the number `53861`, and then just hangs.

Is there any reason we don't have a separate file for this purpose, like `PulumiPolicy.yaml`?

**Comment by joeduffy** [comment] 2019-08-28 22:42
The one benefit I see is that running `pulumi preview` at least tells you if the project compiles.

**Comment by lukehoban** [comment] 2019-08-28 22:58
I think this is related to or the same as https://github.com/pulumi/pulumi-policy/issues/53.

**Comment by joeduffy** [comment] 2019-08-28 23:00
Perhaps, although my read on that issue is "We've decided to use `Pulumi.yaml`, and want to make a series of changes to make that more palatable." I'm questioning whether we should be using it at all.

**Comment by lukehoban** [comment] 2019-08-28 23:02
Yes - I think we should actually close #53 as a dupe of this one.  I personally agree that we likely do not want to re-use `Pulumi.yaml` here.

**Comment by hausdorff** [comment] 2019-08-29 06:24
Quoting from #53 for posterity:

> Policy packs use Pulumi.yaml because (among other things) we wanted to be compatible, eventually with `pulumi new`.
>
> But, several fields in Pulumi.yaml are unused by policy packs. It's work going through and (_e.g._) disallowing the ones that aren't.

So there are two options on the table. We basically kept `Pulumi.yaml` around because (1) it was faster to get started this way, and (2) whatever scheme we used here would (eventually) have to re-use a bunch of stuff that the machinery built around `Pulumi.yaml` already does—things like config values. It seemed weird to ask users to know about 2 or 3 ways that our fancy YAML file machinery works, and to me, it still kind of does. But, this is a hill I'm going to die on, so if we really feel strongly about going this other direction, we can.

**Comment by ekrengel** [comment] 2019-10-02 23:44
Can we prioritize this one @hausdorff ? this will most likely be a breaking change so Id like to fix this sooner than later.

**Comment by joeduffy** [comment] 2019-10-08 22:50
FWIW, just ran into this again -- I tend to run `pulumi preview` when developing a pack to get compiler errors. Is that the suggested workflow?

![image](https://user-images.githubusercontent.com/3953235/66439072-630aa200-e9e3-11e9-8cb6-52e7a313de81.png)

**Comment by hausdorff** [comment] 2019-10-10 17:16
Closed with https://github.com/pulumi/pulumi/pull/3317

**Closed by hausdorff** 2019-10-10 17:16 UTC
Labels: pac/ga
